spring.application.name=auth-service

# Database Configuration
# MongoDB Atlas Configuration
spring.data.mongodb.uri=mongodb+srv://challenge:lPLWxxD3CSWdb8qC@cluster0.tvlir.mongodb.net/leave-management?retryWrites=true&w=majority
spring.data.mongodb.database=leave-management

# Google OAuth2 Configuration
spring.security.oauth2.client.registration.google.client-id=973046799216-u7k7ap8fo5u1h8rt9l2cai5ckq583d2o.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,email,profile
server.forward-headers-strategy=native
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
spring.security.oauth2.client.registration.google.redirect-uri=https://auth-service-production-7c6c.up.railway.app/login/oauth2/code/google

# JWT Configuration
jwt.secret=mrs_secret_key_here_32_chars_long
jwt.expiration=86400000

# Server configuration
server.port=8080