spring.application.name=auth-service

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/auth_service?useSSL=false&serverTimezone=Africa/Kigali&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=rootpassword
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Google OAuth2 Configuration
spring.security.oauth2.client.registration.google.client-id=973046799216-u7k7ap8fo5u1h8rt9l2cai5ckq583d2o.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,email,profile
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google

# JWT Configuration
jwt.secret=mrs_secret_key_here_32_chars_long
jwt.expiration=86400000